/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Henry
 */
public class RegistrarDevolucion extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarDevolucion
     */
    public RegistrarDevolucion() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        UsuariosDisponibles.addActionListener(e -> cargarLibrosDelUsuario());
         cargarUsuariosConPrestamos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarDevolucion = new javax.swing.JButton();
        LibrosPrestados = new javax.swing.JComboBox<>();
        UsuariosDisponibles = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-devolución-de-compra-50.png"))); // NOI18N
        jLabel1.setText("Registrar Devolución");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libro-50.png"))); // NOI18N
        jLabel2.setText("Libro");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-usuario-50 (1).png"))); // NOI18N
        jLabel3.setText("Usuario");

        btnRegistrarDevolucion.setBackground(new java.awt.Color(204, 255, 255));
        btnRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-accede-redondeado-derecho-50 (1).png"))); // NOI18N
        btnRegistrarDevolucion.setText("Registrar Devolución");
        btnRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucionActionPerformed(evt);
            }
        });

        LibrosPrestados.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        UsuariosDisponibles.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuariosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LibrosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrarDevolucion)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UsuariosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LibrosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucionActionPerformed
        String usuarioSeleccionado = (String) UsuariosDisponibles.getSelectedItem();
    String libroSeleccionado = (String) LibrosPrestados.getSelectedItem();

    if (usuarioSeleccionado == null || libroSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario y un libro.");
        return;
    }

    try {
        java.io.File archivoPrestamos = new java.io.File("prestamos.txt");
        java.util.List<String> lineasPrestamos = new java.util.ArrayList<>();
        java.util.Scanner scPrestamos = new java.util.Scanner(archivoPrestamos);

        boolean devolucionExitosa = false;

        while (scPrestamos.hasNextLine()) {
            String linea = scPrestamos.nextLine();
            String[] datos = linea.split(";");

            if (datos.length >= 4) {
               
                if (datos[0].equals(usuarioSeleccionado) && datos[1].equals(libroSeleccionado) && datos[3].equalsIgnoreCase("false")) {
                    
                    linea = datos[0] + ";" + datos[1] + ";" + datos[2] + ";true";
                    devolucionExitosa = true;
                }
            }

            lineasPrestamos.add(linea);
        }
        scPrestamos.close();

        if (!devolucionExitosa) {
            JOptionPane.showMessageDialog(this, "Error: el libro no corresponde al usuario seleccionado o ya fue devuelto.");
            return;
        }

      
        java.io.PrintWriter pwPrestamos = new java.io.PrintWriter(archivoPrestamos);
        for (String l : lineasPrestamos) {
            pwPrestamos.println(l);
        }
        pwPrestamos.close();

        java.io.File archivoLibros = new java.io.File("libros.txt");
        java.util.List<String> lineasLibros = new java.util.ArrayList<>();
        java.util.Scanner scLibros = new java.util.Scanner(archivoLibros);

        while (scLibros.hasNextLine()) {
            String linea = scLibros.nextLine();
            String[] datos = linea.split(";");
            if (datos.length >= 3 && datos[0].equals(libroSeleccionado)) {
                linea = datos[0] + ";" + datos[1] + ";true"; // disponible = true
            }
            lineasLibros.add(linea);
        }
        scLibros.close();

        java.io.PrintWriter pwLibros = new java.io.PrintWriter(archivoLibros);
        for (String l : lineasLibros) {
            pwLibros.println(l);
        }
        pwLibros.close();

        JOptionPane.showMessageDialog(this, "Devolución registrada correctamente.");

        
        cargarUsuariosConPrestamos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar devolución: " + e.getMessage());
    }

    }//GEN-LAST:event_btnRegistrarDevolucionActionPerformed

    private void cargarUsuariosConPrestamos() {
    UsuariosDisponibles.removeAllItems();

    try {
        java.io.File archivoPrestamos = new java.io.File("prestamos.txt");
        java.util.Scanner sc = new java.util.Scanner(archivoPrestamos);

        java.util.Set<String> usuariosConPrestamo = new java.util.HashSet<>();

        while (sc.hasNextLine()) {
            String linea = sc.nextLine();
            String[] datos = linea.split(";");
            // datos[0] = usuario, datos[3] = estado de devolución ("false" = prestado)
            if (datos.length >= 4 && datos[3].equalsIgnoreCase("false")) {
                usuariosConPrestamo.add(datos[0]);
            }
        }
        sc.close();

        for (String usuario : usuariosConPrestamo) {
            UsuariosDisponibles.addItem(usuario);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
    }
}
    
    private void cargarLibrosDelUsuario() {
    LibrosPrestados.removeAllItems();

    String usuarioSeleccionado = (String) UsuariosDisponibles.getSelectedItem();
    if (usuarioSeleccionado == null) return;

    try {
        java.io.File archivoPrestamos = new java.io.File("prestamos.txt");
        java.util.Scanner sc = new java.util.Scanner(archivoPrestamos);

        while (sc.hasNextLine()) {
            String linea = sc.nextLine();
            String[] datos = linea.split(";");
          
            if (datos.length >= 4 && datos[0].equals(usuarioSeleccionado) && datos[3].equalsIgnoreCase("false")) {
                LibrosPrestados.addItem(datos[1]);
            }
        }
        sc.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar libros: " + e.getMessage());
    }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LibrosPrestados;
    private javax.swing.JComboBox<String> UsuariosDisponibles;
    private javax.swing.JButton btnRegistrarDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
